name: CoinMobs
version: v3.0
description: Mobs kills and earn money.
main: cm.joel.main.CoinMobs
author: CinturonCris
api-version: 1.16

depend:
  - Vault
  - Essentials

commands:
  coinmobs:
    description: reload config.
    usage: /coinmobs [reload]
permissions:
  mobcoins.reload:
    description: Reload Config.
    default: op
  mobcoins.head.drop:
    description: Allows players to get heads from mobs
    default: op